name: CampConnect Frontend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build Angular
      run: |
        cd frontend
        npm run build
        
    - name: Build Docker Image
      run: |
        cd frontend
        docker build -t campconnect-frontend .
